name: Deploy to npm

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          registry-url: https://registry.npmjs.org/

      - run: |
          npm ci || npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
