name: Generate docs

on:
  push:
    branches:
      - master

jobs:
  gen-docs:
    name: Generate docs and deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Setup node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build docs
        run: npm run docs

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
